[project]
name = "visidata-plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "visidata",
]

[tool.uv.sources]
visidata = { git = "https://github.com/saulpw/visidata.git", rev = "develop" }
